FROM alpine:3.18.3

RUN mkdir /build

RUN apk add --no-cache \
    go \
    curl \
    build-base \
    meson \
    ninja \
    cfitsio-dev \
    expat-dev \
    fftw-dev \
    giflib-dev \
    glib-dev \
    gobject-introspection-dev \
    lcms2-dev \
    libexif-dev \
    libheif-dev \
    libimagequant-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    libwebp-dev \
    openexr-dev \
    openjpeg-dev \
    orc-dev \
    pango-dev \
    poppler-dev \
    tiff-dev \
    imagemagick \
    imagemagick-dev \
    librsvg-dev \
    libjxl-dev \
    libjxl \
    libjxl-tools \
    cgif-dev \
    tiff-dev \
    aom \
    exiftool 

ARG GOLANGCI_VERSION=1.54.2
RUN cd /build && \
    curl -fsSLO https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-amd64.tar.gz && \
    tar xf golangci-lint-${GOLANGCI_VERSION}-linux-amd64.tar.gz && \
    mv golangci-lint-${GOLANGCI_VERSION}-linux-amd64/golangci-lint /usr/bin/

# ARG CGIF_VERSION=0.3.2
# RUN cd /build && \
#     curl -fsSLO https://github.com/dloebl/cgif/archive/refs/tags/V${CGIF_VERSION}.tar.gz && \
#     tar xf V${CGIF_VERSION}.tar.gz && \
#     cd cgif-${CGIF_VERSION} && \
#     meson setup --prefix=/usr . build && \
#     meson install -C build

ARG VIPS_VERSION=8.14.4
RUN cd /build && \
    curl -fsSLO https://github.com/libvips/libvips/archive/refs/tags/v${VIPS_VERSION}.tar.gz && \
    tar xf v${VIPS_VERSION}.tar.gz && \
    cd libvips-${VIPS_VERSION} && \
    meson setup build --prefix=/usr && \ 
    cd build && meson compile && meson install

RUN cd / && rm -rf /build