enable_sites:
  localhost:8080:
    vendor: aliyun
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket: image-demo
  # bucket domain support
  localhost:8081:
    vendor: aliyun
    endpoint: https://oss-console-img-demo-cn-hangzhou-3az.oss-cn-hangzhou.aliyuncs.com