# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Vendor
      run: go mod vendor

    - name: Test
      run: docker run --rm --name imagecloud-test -v $(pwd):/imagecloud -it songjiayang/govips:v0.2.0 sh -c "cd /imagecloud && go test ./..."
